# This file is a part of DAQCorE.jl, licensed under the MIT License (MIT).

@device_property export ABORt
@device_property export ABRake
@device_property export ACHannel
@device_property export ACK
@device_property export AC
@device_property export ACQuire
@device_property export ACQUire
@device_property export ADD
@device_property export ADDRess
@device_property export ADJust
@device_property export AFC
@device_property export AHLine
@device_property export AILine
@device_property export ALC
@device_property export ALL
@device_property export ALTernate
@device_property export ALWays
@device_property export AMControl
@device_property export AM
@device_property export AMPLitude
@device_property export ANALog
@device_property export ANGLe
@device_property export ANNotation
@device_property export ANO
# @device_property export ANY # conflicts with Main.ANY
@device_property export AOFF
@device_property export APCoeff
@device_property export APERture
@device_property export APOWer
@device_property export APRobe
@device_property export ARRay
@device_property export ASCii
@device_property export ATRigger
@device_property export ATTenuation
@device_property export ATTRibutes
@device_property export AUTO
@device_property export AVERage
@device_property export AWEighting
@device_property export AXIS
@device_property export BACKground
@device_property export BAG
@device_property export BANDwidth
@device_property export BAUD
@device_property export BAVailable
@device_property export BEEPer
@device_property export BESSel
@device_property export BIAS
@device_property export BINary
@device_property export BINertia
@device_property export BIT
@device_property export BITS
@device_property export BLOWer
@device_property export BNO
@device_property export BNUMber
@device_property export BORDer
@device_property export BOTH
@device_property export BOTTom
@device_property export BPASs
@device_property export BRAKe
@device_property export BRIGhtness
@device_property export BRQ
@device_property export BURSt
@device_property export BWIDth
@device_property export CALCulate
@device_property export CAPability
@device_property export CARM
@device_property export CATalog
@device_property export CCIR
@device_property export CCITt
@device_property export CCURve
@device_property export CDFunction
@device_property export CDIRectory
@device_property export CDISable
@device_property export CDOWn
@device_property export CEL
@device_property export CENable
@device_property export CENTer
@device_property export CENTronics
@device_property export CEVent
@device_property export CHEByshev
@device_property export CHECk
@device_property export CLEan
@device_property export CLEar
@device_property export CLIMits
@device_property export CLK
@device_property export CLOCk
@device_property export CLOSe
@device_property export CLR
@device_property export CMAP
@device_property export CMESsage
@device_property export COAX
@device_property export COHerence
@device_property export COLLect
@device_property export COLor
@device_property export COMMand
@device_property export COMMunicate
@device_property export COMPlement
@device_property export COMPlex
@device_property export COMPressor
@device_property export CONCentration
@device_property export CONCurrent
@device_property export CONDition
@device_property export CONFigure
@device_property export CONNect
@device_property export CONTinue
@device_property export CONTinuous
@device_property export CONTrast
@device_property export CONTrol
@device_property export COPY
@device_property export COUNt
@device_property export COUPle
@device_property export COUPling
@device_property export COVer
@device_property export CPOint
@device_property export CPON
@device_property export CREFerence
@device_property export CRESponse
@device_property export CROSs
@device_property export CSET
@device_property export CSIZe
@device_property export CTYPe
@device_property export CURRent
@device_property export CUSTom
@device_property export CUT
@device_property export CW
@device_property export DASHed
@device_property export DATA
@device_property export DATE
@device_property export DC
@device_property export DCOefficient
@device_property export DCONcurrent
@device_property export DCYCle
@device_property export DEFault
@device_property export DEFine
@device_property export DEG
@device_property export DELay
@device_property export DELete
@device_property export DEMPhasis
@device_property export DEPTh
@device_property export DERivative
@device_property export DESTination
@device_property export DETector
@device_property export DEViation
@device_property export DEVice
@device_property export DFACtory
@device_property export DILute
@device_property export DIMensions
@device_property export DINertia
@device_property export DINTerchange
@device_property export DIODe
@device_property export DIRection
@device_property export DISConnect
@device_property export DISTance
@device_property export DISTortion
@device_property export DLASt
@device_property export DLINearize
@device_property export DMODe
@device_property export DNUMber
@device_property export DOS
@device_property export DOTTed
@device_property export DOUBle
@device_property export DOWN
@device_property export DRAW
@device_property export DSEQuence
@device_property export DTOLerance
@device_property export DTR
@device_property export DURation
@device_property export DWELl
@device_property export EBENch
@device_property export ECL
@device_property export ECLTrg
@device_property export ECOunt
@device_property export EDELay
@device_property export EDGE
@device_property export ENABle
@device_property export END
@device_property export ENO
@device_property export ENVelope
@device_property export ERRor
@device_property export EVEN
@device_property export EVENt
@device_property export EXCHange
@device_property export EXCLude
@device_property export EXECute
@device_property export EXPected
@device_property export EXPLicit
@device_property export EXPonential
@device_property export EXPRession
@device_property export EXTernal
@device_property export FACCeptance
@device_property export FAIL
@device_property export FALL
@device_property export FAR
@device_property export FCOunt
@device_property export FCUToff
@device_property export FEED
@device_property export FETCh
@device_property export FFEed
@device_property export FIELd
@device_property export FILTer
@device_property export FIXed
@device_property export FLATtop
@device_property export FLIMits
@device_property export FLOat
@device_property export FORCe
@device_property export FORMat
@device_property export FRAMe
@device_property export FREE
@device_property export FREQuency
@device_property export FRESistance
@device_property export FRONt
@device_property export FSENsor
@device_property export FTIMe
@device_property export FULL
@device_property export FUNCtion
@device_property export GAIN
@device_property export GATE
@device_property export GDAPerture
@device_property export GDEVice
@device_property export GENeration
@device_property export GEOMetry
@device_property export GPIB
@device_property export GRADe
@device_property export GRAPhics
@device_property export GRAPh
@device_property export GRATicule
@device_property export GRID
@device_property export GROund
@device_property export GROup
@device_property export GUARd
@device_property export HAMMing
@device_property export HANNing
@device_property export HARMonic
@device_property export HEADers
@device_property export HELP
@device_property export HEXadecimal
@device_property export HIERarchy
@device_property export HIGH
@device_property export HISTogram
@device_property export HOLD
@device_property export HOLDoff
@device_property export HORizontal
@device_property export HOUR
@device_property export HPASs
@device_property export HPGL
@device_property export HSL
@device_property export HSPeed
@device_property export HYSTeresis
@device_property export IBFull
@device_property export ICLock
@device_property export ICOMmander
@device_property export ICORrection
@device_property export IDLE
@device_property export IDRaw
@device_property export IGNore
@device_property export IMAGinary
@device_property export IMMediate
@device_property export IMOVe
@device_property export IMPedance
@device_property export IMPulse
@device_property export INCLude
@device_property export INFinity
@device_property export INFormation
@device_property export INITialize
@device_property export INITiate
@device_property export INPut
@device_property export INSTrument
@device_property export INTegral
@device_property export INTernal
@device_property export INTerpolate
@device_property export INVerted
@device_property export IQRatio
@device_property export ITEM
@device_property export KBESsel
@device_property export KEY
@device_property export KLOCk
@device_property export LABel
@device_property export LADDress
@device_property export LANDscape
@device_property export LANGuage
@device_property export LATime
@device_property export LAYer
@device_property export LCONstants
@device_property export LDIRection
@device_property export LEADing
@device_property export LEAKage
@device_property export LEFT
@device_property export LENGth
@device_property export LEVel
@device_property export LFRequency
@device_property export LIF
@device_property export LIFT
@device_property export LIMit
@device_property export LINear
@device_property export LINE
@device_property export LINK
@device_property export LISTen
@device_property export LIST
@device_property export LLEFt
@device_property export LLIMit
@device_property export LOAD
@device_property export LOCate
@device_property export LOCation
@device_property export LOCKed
@device_property export LOCK
@device_property export LOGarithmic
@device_property export LOG
@device_property export LOSS
@device_property export LOWer
@device_property export LOW
@device_property export LPASs
@device_property export LPFRame
@device_property export LSB
@device_property export LSET
@device_property export LSPeed
@device_property export LTER
@device_property export LTYPe
@device_property export MACRo
@device_property export MAGNitude
@device_property export MALLocate
@device_property export MANifold
@device_property export MANual
@device_property export MAP
@device_property export MATH
@device_property export MAXimum
@device_property export MCONtrol
@device_property export MEASure
@device_property export MEDium
@device_property export MEDIum
@device_property export MENU
@device_property export MESSage
@device_property export METHod
@device_property export MID
@device_property export MINimum
@device_property export MINute
@device_property export MLINear
@device_property export MLOGarithmic
@device_property export MMHead
@device_property export MODE
@device_property export MODule
@device_property export MOVE
@device_property export MOVing
@device_property export MSIS
@device_property export MULTiplier
@device_property export NAME
@device_property export NAN
@device_property export NCURve
@device_property export NDUTycycle
@device_property export NEGative
@device_property export NEND
@device_property export NEVer
@device_property export NEW
@device_property export NEXT
@device_property export NICHols
@device_property export NINF
@device_property export NONE
@device_property export NORMal
@device_property export NOTCh
@device_property export NPLCycles
@device_property export NRUNs
@device_property export NSELect
@device_property export NSTates
@device_property export NTOLerance
@device_property export NTRansition
@device_property export NUMBer
@device_property export NWIDth
@device_property export NYQuist
@device_property export OCOMpensated
@device_property export OCONdition
@device_property export OCTal
@device_property export ODD
@device_property export OEDGe
@device_property export OFF
@device_property export OFFSet
@device_property export ONCE
@device_property export ONE
@device_property export ON
@device_property export OPEN
@device_property export OPERation
@device_property export ORDinate
@device_property export OREFerence
@device_property export ORIentation
@device_property export OUTPut
@device_property export OVERshoot
@device_property export OWNer
@device_property export PACE
@device_property export PACK
@device_property export PAGE
@device_property export PARallel
@device_property export PARity
@device_property export PASSword
@device_property export PATH
@device_property export PAUSe
@device_property export PCL
@device_property export PCT
@device_property export PDFunction
@device_property export PDIVision
@device_property export PDUTycycle
@device_property export PERCent
@device_property export PERiod
@device_property export PERSistence
@device_property export PHASe
@device_property export PLOSs
@device_property export PMETer
@device_property export POFLag
@device_property export POINt
@device_property export POINts
@device_property export POLarity
@device_property export POLarization
@device_property export PORT
@device_property export PORTrait
@device_property export POSition
@device_property export POSitive
@device_property export POST
@device_property export POSTscript
@device_property export POWer
@device_property export PRBS
@device_property export PREamble
@device_property export PREFerence
@device_property export PRE
@device_property export PRESet
@device_property export PREShoot
@device_property export PRF
@device_property export PROTection
@device_property export PROTocol
@device_property export PSDensity
@device_property export PTPeak
@device_property export PTRansition
@device_property export PULM
@device_property export PWIDth
@device_property export QCLock
@device_property export QCORrection
@device_property export QUADrant
@device_property export QUADrature
@device_property export QUERy
@device_property export QUEStionable
@device_property export RAD
@device_property export RANGe
@device_property export RATio
@device_property export RAW
@device_property export RDEVice
@device_property export READ
@device_property export REALtime
@device_property export REAR
@device_property export RECeive
@device_property export RECTangular
@device_property export REFerence
@device_property export RELease
@device_property export REPeat
@device_property export REPort
@device_property export REQuest
@device_property export RESet
@device_property export RESistance
@device_property export RESolution
@device_property export RESPonse
@device_property export RGB
@device_property export RHANdlers
@device_property export RHLine
@device_property export RIGHt
@device_property export RILine
@device_property export RINTerrupter
@device_property export RISE
@device_property export RLDerivation
@device_property export RLEVel
@device_property export RLINe
@device_property export RLSimulation
@device_property export RMAXimum
@device_property export RMODid
@device_property export RMS
@device_property export ROSCillator
@device_property export ROTation
@device_property export RPERror
@device_property export RPOSition
@device_property export RPRotocol
@device_property export RSARea
@device_property export RSTB
@device_property export RTIMe
@device_property export RTS
@device_property export RUN
@device_property export RVELocity
@device_property export RVERify
@device_property export SAMPle
@device_property export SAVE
@device_property export SBITs
@device_property export SCALar
@device_property export SCALe
@device_property export SCAN
@device_property export SCLOse
@device_property export SCONdition
@device_property export SDEViation
@device_property export SDUMp
@device_property export SEARch
@device_property export SECurity
@device_property export SELected
@device_property export SELect
@device_property export SELF
@device_property export SEND
@device_property export SENSitivity
@device_property export SEQuence
@device_property export SERial
@device_property export SET
@device_property export SHAPe
@device_property export SIGNal
@device_property export SIZE
@device_property export SLEW
@device_property export SLModid
@device_property export SLOCk
@device_property export SLOPe
@device_property export SMOothing
@device_property export SNDRatio
@device_property export SNR
@device_property export SOCKet
@device_property export SOFFset
@device_property export SOLid
@device_property export SOPEn
@device_property export SOURce
@device_property export SPACing
@device_property export SPAN
@device_property export SPEed
@device_property export SPOint
@device_property export SRATional
@device_property export SREGister
@device_property export SSDLoss
@device_property export SSIGnal
@device_property export SSYNchronous
@device_property export STANdard
@device_property export STARt
@device_property export STATe
@device_property export STEP
@device_property export STEPped
@device_property export STIMe
@device_property export STIMulus
@device_property export STOP
@device_property export STORe
@device_property export STRing
@device_property export STYLe
@device_property export SUModid
@device_property export SWAPped
@device_property export SWEep
@device_property export SWR
@device_property export SYNChronous
@device_property export SYNTax
@device_property export TABLe
@device_property export TALign
@device_property export TCONstant
@device_property export TCONtrol
@device_property export TCP
@device_property export TDIameter
@device_property export TDSTamp
@device_property export TEMPerature
@device_property export TEXT
@device_property export THD
@device_property export THReshold
@device_property export TIMe
@device_property export TIME
@device_property export TIMeout
@device_property export TIMer
@device_property export TINertia
@device_property export TINTerval
@device_property export TMAXimum
@device_property export TMINimum
@device_property export TOLerance
@device_property export TOP
@device_property export TOUT
@device_property export TRACe
@device_property export TRACk
@device_property export TRAiling
@device_property export TRANsform
@device_property export TRANsition
@device_property export TRANsmit
@device_property export TRIGgered
@device_property export TRIGger
@device_property export TRIPped
@device_property export TTL
@device_property export TTLTrg
@device_property export TYPE
@device_property export TZONe
@device_property export UDP
@device_property export ULIMit
@device_property export UNIForm
@device_property export UNIT
@device_property export UNLocked
@device_property export UPDate
@device_property export UPHase
@device_property export UP
@device_property export UPPer
@device_property export URIGht
@device_property export USB
@device_property export VALue
@device_property export VCDevice
@device_property export VEHicle
@device_property export VELocity
@device_property export VERBose
@device_property export VERify
@device_property export VERSion
@device_property export VERTical
@device_property export VIDeo
@device_property export VOLTage
@device_property export VOLume
@device_property export VXI
@device_property export WAIT
@device_property export WARMup
@device_property export WAVeguide
@device_property export WEIGht
@device_property export WFACtor
@device_property export WIDTh
@device_property export WINDow
@device_property export WRITe
@device_property export WSPRotocol
@device_property export XON
@device_property export ZERO
